include: package:flutter_lints/flutter.yaml

linter:
  rules:

analyzer: 
  exclude:

    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - '**/*gen.dart'

  errors:
    invalid_annotation_target: ignore
